name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        sudo docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        sudo docker pull alleeeeenm/soha-bot:latest
    - name: Delete Old docker container
      run: sudo docker rm -f soha-bot-container 2>/dev/null || true
    - name: Run Docker Container
      run: sudo docker run -d -p 8000:8000 --name soha-bot-container -v ~/.aws:/root/.aws -v ~/.soha/.env:/app/.env alleeeeenm/soha-bot
